name: weather_app
description: A new Flutter application.
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  weather_icons: ^3.0.0
  geolocator: ^8.2.0
  loader_overlay: ^2.0.5
  provider: ^6.0.2
  dartz: ^0.10.1
  json_annotation: ^4.4.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  shared_preferences: ^2.0.13

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
